### ISSUE TITLE
server generated by go-raml does not work

### ISSUE THREAD

**Issue by nbabenko** [Jumpscale/NOS#6]
Reproduce steps:
1.
 ```
go-raml server -l python --dir ./ --ramlfile ../specs/api.raml
```
2. 
```
python3 app.py
```
Results:
```
nick@nick-XPS-13-9350:~/work/Jumpscale/NOS/server⟫ python3 app.py 
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from reservations import reservations_api
  File "/home/nick/work/Jumpscale/NOS/server/reservations.py", line 4, in <module>
    from ReservationsAclEntriesPostReqBody import ReservationsAclEntriesPostReqBody
ImportError: No module named 'ReservationsAclEntriesPostReqBody'

**Comment by nbabenko** [comment]
outdated already, archiving
